// Code generated by go-bindata. DO NOT EDIT.
// sources:
// assets\china_ip_list.txt
// assets\gfwlist.txt
// assets\private_ip_list.txt

package hsocks5

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestBinData(t *testing.T) {
	bs := MustAsset("assets/private_ip_list.txt")
	assert.True(t, len(bs) > 0)
	info, _ := AssetInfo("assets/private_ip_list.txt")
	assert.False(t, info.IsDir())
	info.Size()
	info.Name()
	info.Mode()
	info.ModTime()
	info.Sys()
	AssetDir("assets")
	assert.True(t, len(AssetNames()) > 0)
}
