name: Snapshot Build
on: [push]
jobs:

  build:
    name: Snapshot Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      working-directory: main
      run: bash build.sh
      
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: SNAPSHOTS-Build
        # Directory containing files to upload
        path: main/build
